image: "python:3.8"
cache:
  paths:
    - .venv/*
before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

stages:
  - Static Analysis
  - Testing

pylint:
  stage: Static Analysis
  script:
    - source .venv/bin/activate
    - pylint -r yes --exit-zero infobserve/ | tee pylint-report.txt
  artifacts:
    paths:
      - pylint-report.txt
  only:
    - merge_requests

mypy:
  stage: Static Analysis
  script:
    - source .venv/bin/activate
    - mypy infobserve/ | tee mypy-report.txt
  artifacts:
    paths:
      - mypy-report.txt
  only:
    - merge_requests

cyclic-complexity:
  stage: Static Analysis
  script:
    - source .venv/bin/activate
    - radon cc -s -n B infobserve/ | tee -a code-metrics.txt
    - radon mi -s -n B infobserve/ | tee -a code-metrics.txt
  artifacts:
    paths:
      - code-metrics.txt
  only:
    - merge_requests

unit-testing:
  stage: Testing
  script:
    - source .venv/bin/activate
    - coverage run --source=infobserve/ -m pytest && coverage report -m | tee coverage.txt
  artifacts:
    paths:
      - coverage.txt
  only:
    - merge_requests
