image: "python:3.8"
cache:
  paths:
    - .venv/*
before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

stages:
  - Static Analysis
  - Testing
  - Sonarqube

pylint:
  stage: Static Analysis
  script:
    - source .venv/bin/activate
    - pylint -r yes --exit-zero infobserve/ | tee pylint-report.txt
  artifacts:
    paths:
      - pylint-report.txt
  only:
    - merge_requests

mypy:
  stage: Static Analysis
  script:
    - source .venv/bin/activate
    - mypy infobserve/ | tee mypy-report.txt
  artifacts:
    paths:
      - mypy-report.txt
  only:
    - merge_requests

cyclic-complexity:
  stage: Static Analysis
  script:
    - source .venv/bin/activate
    - radon cc -s -n B infobserve/ | tee -a code-metrics.txt
    - radon mi -s -n B infobserve/ | tee -a code-metrics.txt
  artifacts:
    paths:
      - code-metrics.txt
  only:
    - merge_requests

unit-testing:
  stage: Testing
  script:
    - source .venv/bin/activate
    - coverage run --source=infobserve/ -m pytest && coverage xml > coverage.xml
    - coverage report -m > coverage.txt
  artifacts:
    paths:
      - coverage.txt
      - coverage.xml
  only:
    - merge_requests
    - develop

sonarqube_mr:
  stage: Sonarqube
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  before_script:
    - echo 0
  script:
    - sonar-scanner
      -Dsonar.projectKey=Infobserve
      -Dsonar.sources=infobserve
      -Dsonar.tests=tests
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.pullrequest.branch=$CI_COMMIT_REF_NAME
      -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_ID
      -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
  dependencies:
    - unit-testing
  allow_failure: true
  only:
    - merge_requests
  tags:
    - homelab

sonarqube_dev:
  stage: Sonarqube
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  before_script:
    - echo 0
  script:
    - sonar-scanner
      -Dsonar.projectKey=Infobserve
      -Dsonar.sources=infobserve
      -Dsonar.tests=tests
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.branch.name=$CI_COMMIT_BRANCH
  dependencies:
    - unit-testing
  allow_failure: true
  only:
    - develop
  tags:
    - homelab
