---
global_scrape_interval: 60
log_level: DEBUG

processing_queue_size: 0

yara_rules_paths:
  - "yara/email/*.yara"
  - "yara/apis/*.yara"

yara_external_vars:
  domain_example: example.com
  localhost_ip: "127.0.0.1"

postgres:
  database: infobserve
  host: postgres
  port: 5432
  user: infobserve
  password: infobserve

redis:
  host: redis
  port: 6379

sources: # only gist source valid for now
  gist:
    scrape_interval: 60
    username: "redacted"
    oauth: "redacted"
