---
global_scrape_interval: 60
log_level: DEBUG

processing_queue_size: 0

yara_rules_paths:
  - "yara/email/*.yara"
  - "yara/apis/*.yara"

yara_external_vars:
  domain_example: example.com
  localhost_ip: "127.0.0.1"

postgres:
  database: database
  host: localhost
  port: 5432
  user: root
  password: root

sources:
  scrape_interval: 30 # Global scrape interval. Affects all sources
  gist:
    scrape_interval: 60 # Overrides global scrape interval
    username: "redacted"
    oauth: "redacted"
  gitlab:
    scrape_interval: 60
    host: self-hosted.gitlab.com
    access_token: "redacted"
