version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: infobserve
      POSTGRES_PASSWORD: infobserve
      POSTGRES_DB: infobserve
    networks:
      - infobserve
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    networks:
      - infobserve
    ports:
      - "6379:6379"

  infobserve:
    build: .
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python main.py'
    networks:
      - infobserve
    depends_on:
      - postgres

networks:
  infobserve:
