[tool.poetry]
name = "Infobserve"
version = "0.1.0"
description = ""
authors = ["Mikts <mikts94@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pylint = "^2.4"
yapf = "^0.29.0"
asyncpg = "^0.20.1"
gidgethub = "^3.2"
aiohttp = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
yapf = "^0.29.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
