# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on:
      - linux

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.5"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install
      - name: Static Analysis
        run: |
          source .venv/bin/activate
          pylint -r yes --exit-zero infobserve/ | tee pylint-report.txt
          mypy infobserve/ | tee mypy-report.txt
          radon cc -s -n B infobserve/ | tee -a code-metrics.txt
          radon mi -s -n B infobserve/ | tee -a code-metrics.txt
      - name: Testing
        run: |
          source .venv/bin/activate
          coverage run --source=infobserve/ -m pytest && coverage xml > coverage.xml
